spring:
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**

  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: default

logging:
  level:
    root: info
    com.example: debug
  file:
    name: log/blog.log

server:
  port: 8083

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: t_
  configuration:
    map-underscore-to-camel-case: true

comment:
  avatar: /images/bg.png

